site_name: TAP Workshops
site_url: https://joostvdg.github.io/tap-workshops/
site_description: Site for examples and guides related to VMware Tanzu products and OSS projects
docs_dir: docs/
repo_name: joostvdg/tap-workshops
repo_url: https://github.com/joostvdg/tap-workshops
edit_uri: ''
copyright: 'Copyright &copy; 2023 Joost van der Griendt'

# Theme
# Configuration
theme:
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy
  name: material
  language: 'en'
  icon:
    logo: material/cloud
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  font:
    text: 'Roboto'
    code: 'JetBrains Mono'

plugins:
  - tags
  - git-revision-date-localized:
      type: iso_datetime
  - search
  - minify:
      minify_html: true

extra:
  generator: false
  version:
    method: mike
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/joostvdg
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/joost_vdg
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/joostvdg

# Extensions
markdown_extensions:
  - abbr
  - footnotes
  - admonition
  - codehilite:
      linenums: true
      guess_lang: true
  - meta
  - tables
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
- HOME: index.md
- Labs:
  - labs.md
  - install/basic.md
  - apps/hello-world.md
  - supply-chain/custom.md  
  - supply-chain/basic-to-test-scan.md
  - apps/external-service.md
- Installation:
  - install/basic.md
  - install/gitops.md
  - install/mutlicluster.md
- Applications:
  - apps/hello-world.md
  - apps/external-service.md
  - apps/where-for-dinner.md
- SupplyChains:
  - supply-chain/custom.md  
  - supply-chain/basic-to-test-scan.md
- Customizations:
  - custom/accelerator.md.md