apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: source-code-supply-chain-01
spec:
  resources:
    - name: build-image
      templateRef:
        kind: ClusterImageTemplate
        name: image-builder-01
    - name: deploy
      templateRef:
        kind: ClusterTemplate
        name: app-deploy-from-sc-image-01
      images:
        - resource: build-image
          name: built-image

  serviceAccountRef:
    name: cartographer-from-source-sa
    namespace: dev

  selector:
    workload-type: source-code-01